//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_v3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SearchBaseEntities : DbContext
    {
        public SearchBaseEntities()
            : base("name=SearchBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TCatalog> TCatalog { get; set; }
        public virtual DbSet<TFile> TFile { get; set; }
        public virtual DbSet<TSearchPattern> TSearchPattern { get; set; }
        public virtual DbSet<TUser> TUser { get; set; }
    }
}
