//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_v3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFile
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string keywords { get; set; }
        public Nullable<double> size { get; set; }
        public string format { get; set; }
        public string content { get; set; }
        public Nullable<int> IdCatalog { get; set; }
    
        public virtual TCatalog TCatalog { get; set; }
    }
}
